### ISSUE TITLE
419 response when uploaded in server

### ISSUE THREAD

**Issue by fadilaksal** [hussein4alaa/laravel-g4t-swagger-auto-generate#26]
Hello, 
first of all, thank you for making this amazing project, I want to ask about the problems I'm experiencing,
when it was up on the server, and tried the route to `post`, the response I got was `419`

when i check in the response, it return `CSRF token mismatch`.

but previously it ran smoothly when I tried it in the local environment

Are there any additional settings that i miss?
Just for information, I use Laravel 10

Thank You

**Comment by hussein4alaa** [comment]
Open app\Http\Middleware\VerifyCsrfToken.php
Add the paths that you want to exclude from CSRF validations inside this:
    protected $except = [
        //
    ];
