### ISSUE TITLE
i want to add description for apis in swagger  , and i want to  edit '200 successful operation' in swagger

### ISSUE THREAD

**Issue by raju-sah** [hussein4alaa/laravel-g4t-swagger-auto-generate#31]
i want to add description for apis in swagger  , and i want to  edit '200 successful operation' in swagger

**Comment by hussein4alaa** [comment]
@raju-sah Currently, there isn't a way to add a description for APIs in Swagger or edit the "200 Successful Operation" in Swagger.
However, these features might be added in the upcoming update of Swagger. 
I'll make sure to include them in the next update and inform you accordingly.

**Comment by hussein4alaa** [comment]
Dear @raju-sah,
please do the following steps: 
- remove `config/swagger.php`
- please re-install package
- in routes add this ->description('........'); like this:
   ```
   Route::get('user', [UserController::class, 'index'])->description('get list of users with pagination.');
   ```
- and you can customize responses from `config/swagger.php`
