### ISSUE TITLE
Failed to open stream: No such file or directory & Trait "G4T\Swagger\Helpers" not found

### ISSUE THREAD

**Issue by milantarami** [hussein4alaa/laravel-g4t-swagger-auto-generate#4]
i am using laravel sail when i try to install the package i got the following errors

` require(/var/www/html/vendor/g4t/swagger/src/routes/web.php): Failed to open stream: No such file or directory`

![image](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/44134655/92c94660-5694-49f5-85de-7e5d4be6a535)

**solution**

looks like a case sensitive issue when i rename a folder `src/Routes` to `src/routes` and run command `sail composer dump-autoload` package get installed 

**After then i got another issue**

When i navigate to route `swagger/documentation` i got following error

`Trait "G4T\Swagger\Helpers" not found`

**Comment by hussein4alaa** [comment]
I am very sorry that you encountered this problem
And thank you for telling me and helping me to solve it
Released version 1.0.2 free of this problem
Thank you for your contribution to improving it
