### ISSUE TITLE
Map Enums in  Request as select dropdown in swagger documentation

### ISSUE THREAD

**Issue by raju-sah** [hussein4alaa/laravel-g4t-swagger-auto-generate#40]
This is the Enum JourneyType:
<?php  namespace App\Enums;  enum JourneyType: string {     case Trekking = 'trekking';     case Tour = 'tour';     case Travel = 'travel';     case Adventure = 'adventure'; }

the below is Request:
 'type' => ['nullable', 'string', new Enum(JourneyType::class)],

now  i want to have these enums as select dropdown in swagger if it is possible?

because it simplify the documentation process.

Thank you in advance.

Happy Coding !!!!!!!.

**Comment by hussein4alaa** [comment]
Hello @raju-sah ,
Can you provide me `JourneyType` content?
I will work to make it supported.

**Comment by raju-sah** [comment]
here it is:
<?php

namespace App\Enums;

enum JourneyType: string
{
    case Trekking = 'trekking';
    case Tour = 'tour';
    case Travel = 'travel';
    case Adventure = 'adventure';
}

**Comment by raju-sah** [comment]
enum JourneyType: string
{
    case Trekking = 'trekking';
    case Tour = 'tour';
    case Travel = 'travel';
    case Adventure = 'adventure';
}

**Comment by hussein4alaa** [comment]
> enum JourneyType: string { case Trekking = 'trekking'; case Tour = 'tour'; case Travel = 'travel'; case Adventure = 'adventure'; }

Thank you, I will be sure to support it very soon.

**Comment by raju-sah** [comment]
okay, thank you in advance!!!!

**Comment by hussein4alaa** [comment]
Dear @raju-sah  Please upgrade the package to [3.0.9](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/tree/3.0.9)
It will work fine
Thank you for submitting suggestion report

![carbon](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/13614747/5b6f3c06-8bb8-4a6d-a758-798e3afaca53)

![carbon (1)](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/13614747/b2842986-89aa-4fdc-bdee-9853024acd78)

![carbon3](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/13614747/5d31c24a-7503-4bcd-b403-47e54aa69d4a)
