### ISSUE TITLE
In validation integer type showing string in swagger

### ISSUE THREAD

**Issue by raju-sah** [hussein4alaa/laravel-g4t-swagger-auto-generate#42]
![image](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/91242760/7d5bd1d6-c7d9-4caa-b0da-c3cde8c3ebb4)

this is my validation rule:
 return [
            'per_page' => 'nullable|integer',
        ];

**Comment by hussein4alaa** [comment]
Dear @raju-sah  Please upgrade the package to [3.1](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/tree/3.1.0)
It will work fine
Thank you for submitting a bug report
