### ISSUE TITLE
Enum validation issue gives this error: str_contains(): Argument #1 ($haystack) must be of type string, array given

### ISSUE THREAD

**Issue by raju-sah** [hussein4alaa/laravel-g4t-swagger-auto-generate#47]
public function rules(): array
    {
        return [
            'type' => ['nullable', 'string', new Enum(JourneyType::class)],
        ];
    }
in this i got this issue:
![image](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/91242760/1ba86eb6-2672-48b8-a936-6ce14649e154)

**Comment by hussein4alaa** [comment]
@raju-sah After reviewing, I did not find any problem.
Please go here http://base_url /swagger/issues
Send me what appears to you
