### ISSUE TITLE
Add option to configure base controller namespace.

### ISSUE THREAD

**Issue by dusanbre** [hussein4alaa/laravel-g4t-swagger-auto-generate#54]
Add option to configure base controller namespace.
For example, that the package controller does not extend the default laravel abstract controller namespace but extends the controller namespace that is configured in the config file.

 The use case is that I have a project that has a custom structure, the base controller is located under a different namespace, and that's why the package gives you an error.

Btw, the best package for api docs in laravel ecosystem 👍 
![Screenshot 2024-07-03 at 10 47 29](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/55688658/f6ec322d-b92f-421d-801e-d6640b1135b7)

**Comment by hussein4alaa** [comment]
Dear @dusanbre ,
now you can use [3.1.9](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/releases/tag/3.1.9) the issue has been resolved in this release.
Thank you for helping me make this package better.
