### ISSUE TITLE
Class "App\Http\Controllers\Controller" not found error in a modular project

### ISSUE THREAD

**Issue by mohammadsalehnia** [hussein4alaa/laravel-g4t-swagger-auto-generate#59]
Hi, I'm using a Laravel 10 application with the nWidart/laravel-modules package and a customized directory for my application. So there is no file in App\Http\Controllers\Controller.

After installing [laravel-g4t-swagger-auto-generate](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate) 
I've got this error:
Class "App\Http\Controllers\Controller" not found
<img width="1507" alt="Screenshot 2024-07-04 at 9 42 25 PM" src="https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/assets/12606608/129203d8-9576-4984-ae10-41175226d746">

Can a different Controller file be used as the default Controller for this package?

**Comment by hussein4alaa** [comment]
Dear @mohammadsalehnia,
now you can use [3.1.9](https://github.com/hussein4alaa/laravel-g4t-swagger-auto-generate/releases/tag/3.1.9) the issue has been resolved in this release.
Thank you for helping me make this package better.
