### ISSUE TITLE
Swagger 'Authorize' not working

### ISSUE THREAD

**Issue by mouayed-keziz** [hussein4alaa/laravel-g4t-swagger-auto-generate#70]
**Describe the bug**
in the swagger ui, when opening the authorize section and add an apiKey or a bearer token it doesnt work, i have a working api (auth with sanctum) with laravel, tested with http clients (curl, postman, httpie) and everything works fine, when using the authorize feature of swagger it doesnt add the token to the req

by default the config has two authorization strategies, which are
```php
"authorization" => [
            "type" => "apiKey",
            "name" => "authorization",
            "in" => "header"
        ],
        "apiKey1" => [
            "type" => "apiKey",
            "name" => "key1",
            "in" => "query"
        ],
```
i added this one 
```php
"bearer" => [
            "type" => "http",
            "scheme" => "bearer",
            "bearerFormat" => "JWT",
            "securityScheme" => "bearerAuth",
            "description" => "Enter the token with the Bearer prefix, e.g. `Bearer abcde12345`"
        ]
```
but when trying to make a request after adding a key (both default strategies or my custom one), the backend responds with 'Unauthorized', when looking at the curl request, it seems like the swagger is not even adding the headers to the request
```bash
curl -X 'GET' \
  'http://localhost:8000/api/v1/user/get-infos' \
  -H 'accept: application/json'
```

**To Reproduce**
1. open the swagger ui
2. add a key the authorize modal (doesnt matter if its apiKey, bearer)
3. try to send a request to an endpoing
4. read the curl output (the issue is that it doesnt add anything to the request)

**Expected behavior**
having the actual token in the request, and having the correct response from the server (authorized)

**Screen Shots**
![image](https://github.com/user-attachments/assets/cf347911-237b-4b01-b458-a4171fcd0042)
![image](https://github.com/user-attachments/assets/ccd8bb1f-879d-4c0c-839d-e3e537ab0d50)

**Comment by hussein4alaa** [comment]
dear @mouayed-keziz 
edit `config/swagger.php`
to add `auth_middlewares`
![sanctum](https://github.com/user-attachments/assets/85c3416c-321c-48e6-a4c6-4a51e5053a4f)

and use default `security_schemes`
![auth](https://github.com/user-attachments/assets/be0df9a2-42ee-4df8-a3a3-40724b1d243d)
![ss](https://github.com/user-attachments/assets/eafd7f3b-da98-4785-95bd-329dcb5f24e1)
